@extends('layouts.employee')

@section('breadcrumb')
    Invoice: {{ $invoice->id }}
@endsection

@section('main-content')
    <p class="h4 mt-4">Invoice Details</p>
    <div class="container-fluid row border-top border-bottom py-4">
        <div class="col ps-0 border-end">
            <p>Invoice ID: <span class="fw-bold">{{ $invoice->id }}</span></p>
            <p>Invoice Generated By: <span class="fw-bold">{{ $invoice->emp_name }}</span></p>
            <p>Total Amount: <span class="fw-bold">{{ $invoice->total_amount }}</span></p>
            <p>Invoice Date: <span class="fw-bold">{{ $invoice->created_at }}</span></p>
        </div>
        <div class="col pe-0">
            <p>Customer Name: <span class="fw-bold">{{ $invoice->customer_name }}</span></p>
            <p>Customer Mobile: <span class="fw-bold">{{ $invoice->customer_mobile }}</span></p>
            <p>Total Items: <span class="fw-bold">{{ $invoice->products->count() }}</span></p>
            <p class="mb-0">
                <a href="{{ route('employee.invoices.print', $invoice->id) }}" class="btn btn-sm btn-primary">
                    <i class="fa-solid fa-print me-2"></i>
                    Print Invoice
                </a>
            </p>
        </div>
    </div>
    <table class="table table-bordered text-center mt-4">
        <thead>
            <th class="bg-light">#</th>
            <th class="bg-light">Name</th>
            <th class="bg-light">SKU</th>
            <th class="bg-light">Quantity</th>
            <th class="bg-light">Price</th>
            <th class="bg-light">Total Price</th>
        </thead>
        <tbody>
            @foreach ($invoice->products as $product)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $product->product_name }}</td>
                    <td>{{ $product->SKU }}</td>
                    <td>{{ $product->quantity }}</td>
                    <td>{{ $product->price }}</td>
                    <td>{{ $product->total_price }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="text-end">
        <p>Total Amount: <span class="fw-bold fs-4">{{ $invoice->total_amount }}</span></p>
    </div>
@endsection
